document:
  name: Guida al Catalogo nazionale della semantica dei dati

  description: Questa guida raccoglie indicazioni per le Pubbliche Amministrazioni per consultare e contribuire ai contenuti semantici del Catalogo schema.gov.it
  tags:
    - interoperabilità
    - API
    - semantica
    - dati
