# -*- coding: utf-8 -*-
#
# Sphinx RTD theme demo documentation build configuration file, created by
# sphinx-quickstart on Sun Nov  3 11:56:36 2013.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# -- PROJECT Variables ----------------------------------------------------
settings_project_name = "Catalogo Nazionale Dati per l'Interoperabilità Semantica"
settings_copyright_copyleft = "Dipartimento per la Trasformazione Digitale"
settings_editor_name = "Dipartimento per la Trasformazione Digitale"
settings_doc_version = ""
settings_doc_release = ""
settings_basename = "dati-semantic-guida-sviluppo"
settings_file_name = "dati-semantic-guida-sviluppo"
settings_discourse_url = "https://forum.italia.it/"

#import docs_italia_theme

import sys
sys.path.append('../')

import docs_italia_theme

#########

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
    "sphinx.ext.doctest",
    "docs_italia_theme",
    "myst_parser",
    "sphinxcontrib.mermaid",
]

# The suffix of source filenames.
source_suffix = [".md", ".rst"]

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "docs_italia_theme"

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = [docs_italia_theme.get_html_theme_path()]

# General information about the project.
project = settings_project_name
copyright = settings_copyright_copyleft

# URL of Discourse instance used by sphinxcontrib.discourse extension
discourse_url = settings_discourse_url

# The short X.Y version.
version = settings_doc_version
# The full version, including alpha/beta/rc tags.
release = settings_doc_release

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = "it"

# Output file base name for HTML help builder.
htmlhelp_basename = settings_basename + "doc"

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ("index", settings_file_name, settings_project_name, [settings_editor_name], 1)
]

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        "index",
        settings_file_name,
        settings_project_name,
        settings_copyright_copyleft,
        settings_project_name,
        settings_project_name,
        "Miscellaneous",
    )
]

numfig = True
